EUWeb/EUWeb/Controllers/ArticleController.cs
using EU.BLL;
using EU.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EUWeb.Controllers
{
    /// <summary>
    /// 文章
    /// </summary>
    //[Authorize]
    public class ArticleController : Controller
    {
        private InterfaceArticleService articleService;
        private InterfaceCommonModelService commonModelService;
        public ArticleController() {
            articleService = new ArticleService();
            commonModelService = new CommonModelService();
        }
        // GET: Article
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 添加文章
        /// </summary>
        /// <returns>视图页面</returns>
        //[ValidateInput(false)]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Add(Article article)
        {
            if (ModelState.IsValid)
            {
                CommonModel commonModel = new CommonModel();
                commonModel.Hits = 0;
                commonModel.Inputer = User.Identity.Name;
                commonModel.Model = "Article";
                commonModel.ReleaseDate = System.DateTime.Now;
                commonModel.Status = 99;
                article.CommonModel = commonModel;
                article = articleService.Add(article);
                if (article.ArticleID > 0)
                {
                    //附件处理
                    InterfaceAttachmentService _attachmentService = new AttachmentService();
                    //查询相关附件
                    var _attachments = _attachmentService.FindList(null, User.Identity.Name, string.Empty).ToList();
                    //遍历附件
                    foreach (var _att in _attachments)
                    {
                        var _filePath = Url.Content(_att.FilePath);
                        //文章首页图片或内容中使用了该附件则更改ModelID为文章保存后的ModelID
                        if ((article.CommonModel.DefaultPicUrl != null && article.CommonModel.DefaultPicUrl.IndexOf(_filePath) >= 0) || article.Content.IndexOf(_filePath) > 0)
                        {
                            _att.ModelID = article.ModelID;
                            _attachmentService.Update(_att);
                        }
                        //未使用改附件则删除附件和数据库中的记录
                        else
                        {
                            System.IO.File.Delete(Server.MapPath(_att.FilePath));
                            _attachmentService.Delete(_att);
                        }
                    }
                    //return View("AddSucess", article);
                }
            }
            return View();
        }
        /// <summary>
        /// 文章列表Json【注意权限问题，普通人员是否可以访问？】
        /// </summary>
        /// <param name="title">标题</param>
        /// <param name="input">录入</param>
        /// <param name="category">栏目</param>
        /// <param name="fromDate">日期起</param>
        /// <param name="toDate">日期止</param>
        /// <param name="pageIndex">页码</param>
        /// <param name="pageSize">每页记录</param>
        /// <returns></returns>
        public ActionResult JsonList(string title, string input, Nullable<int> category, Nullable<DateTime> fromDate, Nullable<DateTime> toDate, int pageIndex = 1, int pageSize = 20)
        {
            if (category == null) category = 0;
            int _total;
            var _rows = commonModelService.FindPageList(out _total, pageIndex, pageSize, "Article", title, (int)category, input, fromDate, toDate, 0).Select(
                cm => new EUWeb.Models.CommonModelViewModel()
                {
                    CategoryID = cm.CategoryID,
                    CategoryName = "123",//cm.Category.Name,
                    DefaultPicUrl = cm.DefaultPicUrl,
                    Hits = cm.Hits,
                    Inputer = cm.Inputer,
                    Model = cm.Model,
                    ModelID = cm.ModelID,
                    ReleaseDate = cm.ReleaseDate,
                    Status = cm.Status,
                    Title = cm.Title
                });
            return Json(new { total = _total, rows = _rows.ToList() });
        }
        /// <summary>
        /// 全部文章
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return View();
        }
    }
}

EUWeb/EUWeb/Controllers/AttachmentController.cs
using EU.BLL;
using EU.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EUWeb.Controllers
{
    /// <summary>
    /// 附件
    /// </summary>
    [Authorize]
    public class AttachmentController : Controller
    {
        AttachmentService attachmentService = new AttachmentService();
        // GET: Attachment
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 上传附件
        /// </summary>
        /// <returns></returns>
        public ActionResult Upload()
        {
            var _uploadConfig = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("~").GetSection("UploadConfig") as EUWeb.Models.Config.UploadConfig;
            //文件最大限制
            int _maxSize = _uploadConfig.MaxSize;
            //保存路径
            string _savePath;
            //文件路径
            string _fileParth = "~/" + _uploadConfig.Path + "/";
            //文件名
            string _fileName;
            //扩展名
            string _fileExt;
            //文件类型
            string _dirName;
            //允许上传的类型
            Hashtable extTable = new Hashtable();
            extTable.Add("image", _uploadConfig.ImageExt);
            extTable.Add("flash", _uploadConfig.FileExt);
            extTable.Add("media", _uploadConfig.MediaExt);
            extTable.Add("file", _uploadConfig.FileExt);
            //上传的文件
            HttpPostedFileBase _postFile = Request.Files["imgFile"];
            if (_postFile == null) return Json(new { error = '1', message = "请选择文件" });
            _fileName = _postFile.FileName;
            _fileExt = Path.GetExtension(_fileName).ToLower();
            //文件类型
            _dirName = Request.QueryString["dir"];
            if (string.IsNullOrEmpty(_dirName))
            {
                _dirName = "image";
            }
            if (!extTable.ContainsKey(_dirName)) return Json(new { error = 1, message = "目录类型不存在" });
            //文件大小
            if (_postFile.InputStream == null || _postFile.InputStream.Length > _maxSize) return Json(new { error = 1, message = "文件大小超过限制" });
            //检查扩展名
            if (string.IsNullOrEmpty(_fileExt) || Array.IndexOf(((string)extTable[_dirName]).Split(','), _fileExt.Substring(1).ToLower()) == -1) return Json(new { error = 1, message = "不允许上传此类型的文件。 \n只允许" + ((String)extTable[_dirName]) + "格式。" });
            _fileParth += _dirName + "/" + DateTime.Now.ToString("yyyy-MM") + "/";
            _savePath = Server.MapPath(_fileParth);
            //检查上传目录
            if (!Directory.Exists(_savePath)) Directory.CreateDirectory(_savePath);
            string _newFileName = DateTime.Now.ToString("yyyyMMdd_hhmmss") + _fileExt;
            _savePath += _newFileName;
            _fileParth += _newFileName;
            //保存文件
            _postFile.SaveAs(_savePath);
            //保存数据库记录
            Attachment attachment = new Attachment()
            {
                Extension = _fileExt.Substring(1),
                FilePath = _fileParth,
                Owner = User.Identity.Name,
                UploadDate = DateTime.Now,
                Type = _dirName
            };           
            attachmentService.Add(attachment);
            return Json(new { error = 0, url = Url.Content(_fileParth) });
        }
        /// <summary>
        /// 附件管理列表
        /// </summary>
        /// <param name="id">公共模型ID</param>
        /// <param name="dir">目录（类型）</param>
        /// <returns></returns>
        public ActionResult FileManagerJson(int? id, string dir)
        {
            EUWeb.Areas.Member.Models.AttachmentManagerViewModel _attachmentViewModel;
            IQueryable<Attachment> _attachments;
            //id为null，表示是公共模型id为null，此时查询数据库中没有跟模型对应起来的附件列表（以上传，但上传的文章……还未保存）
            if (id == null) _attachments = attachmentService.FindList(null, User.Identity.Name, dir);
            //id不为null，返回指定模型id和id为null（新上传的）附件了列表
            else _attachments = attachmentService.FindList((int)id, User.Identity.Name, dir, true);
            //循环构造AttachmentManagerViewModel
            var _attachmentList = new List<EUWeb.Areas.Member.Models.AttachmentManagerViewModel>(_attachments.Count());
            foreach (var _attachment in _attachments)
            {
                _attachmentViewModel = new EUWeb.Areas.Member.Models.AttachmentManagerViewModel() { datetime = _attachment.UploadDate.ToString("yyyy-MM-dd HH:mm:ss"), filetype = _attachment.Extension, has_file = false, is_dir = false, is_photo = _attachment.Type.ToLower() == "image" ? true : false, filename = Url.Content(_attachment.FilePath) };
                FileInfo _fileInfo = new FileInfo(Server.MapPath(_attachment.FilePath));
                _attachmentViewModel.filesize = (int)_fileInfo.Length;
                _attachmentList.Add(_attachmentViewModel);
            }
            return Json(new { moveup_dir_path = "", current_dir_path = "", current_url = "", total_count = _attachmentList.Count, file_list = _attachmentList }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 创建缩略图
        /// </summary>
        /// <param name="originalPicture">原图地址</param>
        /// <returns>缩略图地址。生成失败返回null</returns>
        public ActionResult CreateThumbnail(string originalPicture)
        {
            //原图为缩略图直接返回其地址
            if (originalPicture.IndexOf("_s") > 0) return Json(originalPicture);
            //缩略图地址
            string _thumbnail = originalPicture.Insert(originalPicture.LastIndexOf('.'), "_s");
            //创建缩略图
            if (Helpers.Picture.CreateThumbnail(Server.MapPath(originalPicture), Server.MapPath(_thumbnail), 160, 120))
            {
                //记录保存在数据库中
                attachmentService.Add(new Attachment() { Extension = _thumbnail.Substring(_thumbnail.LastIndexOf('.') + 1), FilePath = "~" + _thumbnail, Owner = User.Identity.Name, Type = "image", UploadDate = DateTime.Now });
                return Json(_thumbnail);
            }
            return Json(null);
        }
    }
}

EUWeb/EUWeb/Controllers/CategoryController.cs
using EU.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EUWeb.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private InterfaceCategoryService categoryRepository;
        public CategoryController() {
            categoryRepository = new CategoryService();
        }
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult JsonTree()
        {
            return View();
        }
    }
}

EUWeb/EUWeb/Views/Article/Add.cshtml
@Styles.Render("~/Scripts/jquery-easyui-1.4.5/themes/default/easyui.css")
@*@Scripts.Render("~/Scripts/jquery-easyui-1.4.5/themes/icon.css")*@
@section scripts{
    <script type="text/javascript" src="~/KindEditor/kindeditor-min.js"></script>
    <script type="text/javascript">
            //编辑框
            KindEditor.ready(function (K) {
                window.editor = K.create('#Content', {
                    height: '500px',
                    uploadJson: '@Url.Action("Upload","Attachment")',
                    fileManagerJson: '@Url.Action("FileManagerJson","Attachment")',
                    allowFileManager: true,
                    formatUploadUrl:false
                });
                //首页图片
                var editor2 = K.editor({
                    fileManagerJson: '@Url.Action("FileManagerJson", "Attachment")'
                });
                K('#btn_picselect').click(function () {
                    editor2.loadPlugin('filemanager', function () {
                        editor2.plugin.filemanagerDialog({
                            viewType: 'VIEW',
                            dirName: 'image',
                            clickFn: function (url, title) {
                                var url;
                                $.ajax({
                                    type: "post",
                                    url: "@Url.Action("CreateThumbnail", "Attachment")",
                                    data: { originalPicture: url },
                                async: false,
                                success: function (data) {
                                    if (data == null) alert("生成缩略图失败！");
                                    else {
                                        K('#CommonModel_DefaultPicUrl').val(data);
                                        K('#imgpreview').attr("src", data);
                                    }
                                    editor2.hideDialog();
                                }
                             });
                            }
                        });
                    });
                });
            });            
    </script>
}

@model  EU.Models.Article
@using (Html.BeginForm())
{ @Html.AntiForgeryToken()
    <div class="form-horizontal" role="form">
        <h4>添加文章</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <label class="control-label col-sm-2" for="CommonModel_CategoryID">栏目</label>
            <div class="col-sm-10">
                <input id="CommonModel_CategoryID" name="CommonModel.CategoryID" data-options="url:'@Url.Action("JsonTree", "Category", new { model="Article" })'" class="easyui-combotree" style="height: 34px; width: 280px;" />
                @Html.ValidationMessageFor(model => model.CommonModel.CategoryID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CommonModel.Title, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.CommonModel.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CommonModel.Title)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Author, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.Author, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Author)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Source, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.Source, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Source)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Intro, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.TextAreaFor(model => model.Intro, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Intro)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommonModel.DefaultPicUrl, new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                <img id="imgpreview" class="thumbnail" src="" />
                @Html.HiddenFor(model => model.CommonModel.DefaultPicUrl)
                <a id="btn_picselect" class="easyui-linkbutton">选择…</a>
                @Html.ValidationMessageFor(model => model.CommonModel.DefaultPicUrl)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="添加" class="btn btn-default" />
            </div>
        </div>
    </div>
}

EUWeb/EUWeb/Views/Article/List.cshtml
@model  EU.Models.Article

<div id="toolbar">
    <div>
        <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true">修改</a>
        <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true" ">删除</a>
        <a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-reload',plain:true" onclick="$('#article_list').datagrid('reload');">刷新</a>
    </div>
    <div class="form-inline">
        <label>栏目</label><input id="combo_category" data-options="url:'@Url.Action("JsonTree", "Category", new { model="Article" })'" class="easyui-combotree" />
        <label>标题</label> <input id="textbox_title" class="input-easyui" style="width:280px" />
        <label>录入人</label><input id="textbox_inputer" class="input-easyui" />
        <label>添加日期</label>
        <input id="datebox_fromdate" type="datetime" class="easyui-datebox" style="width:120px" /> -
        <input id="datebox_todate" type="datetime" class="easyui-datebox" style="width:120px; " />
        <a href="#" id="btn_search" data-options="iconCls:'icon-search'" class="easyui-linkbutton">查询</a>
    </div>

</div>
<table id="article_list"></table>
<link rel="stylesheet" type="text/css" href="~/Scripts/jquery-easyui-1.4.5/themes/default/easyui.css">
<link rel="stylesheet" type="text/css" href="~/Scripts/jquery-easyui-1.4.5/themes/icon.css">
@*<link rel="stylesheet" type="text/css" href="~/demo.css">*@
<script type="text/javascript" src="~/Scripts/jquery-1.11.3.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-ui-1.11.4.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-easyui-1.4.5/jquery.easyui.min.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-easyui-1.4.5/plugins/jquery.datagrid.js"></script>
<script type="text/javascript">
    $().ready(function () {
        $("#article_list").datagrid({
            loadMsg: '加载中……',
            pagination: true,
            url: '@Url.Action("JsonList","Article")',
            columns: [[
                { field: 'ModelID', title: 'ID', checkbox: true },
                { field: 'CategoryName', title: '栏目' },
                { field: 'Title', title: '标题' },
                { field: 'Inputer', title: '录入', align: 'right' },
                { field: 'Hits', title: '点击', align: 'right' },
                { field: 'ReleaseDate', title: '发布日期', align: 'right', formatter: function (value, row, index) { return jsonDateFormat(value); } },
                { field: 'StatusString', title: '状态', width: 100, align: 'right' }
            ]],
            toolbar: '#toolbar',
            idField: 'ModelID',
        });
        //查找
        $("#btn_search").click(function () {
            $("#article_list").datagrid('load', {
                title: $("#textbox_title").val(),
                input: $("#textbox_inputer").val(),
                category: $("#combo_category").combotree('getValue'),
                fromDate: $("#datebox_fromdate").datebox('getValue'),
                toDate: $("#datebox_todate").datebox('getValue')
            });
        });
    });
       
</script>